In [3]:
#1]
import numpy as np
a=np.arange(2,51,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [13]:
#2]
arr1,arr2 = (list(map(int,input().split())) for i in range(2))

arr1 = np.array(arr1)
arr2 = np.array(arr2)

print(np.concatenate((arr1,arr2)))

print(np.sort(np.concatenate((arr1,arr2))))

1 2 5
3 7 9
[1 2 5 3 7 9]
[1 2 3 5 7 9]


In [11]:
#3]
arr = np.array([ [1,2,3,4] , [4,5,6,7] , [7,8,9,0] ])

print(arr.shape)
print(arr.size)

(3, 4)
12


In [14]:
#4]
arr = np.array([ [1,2,3,4,5,6,7,8,9] ])

print(arr,arr.shape) 

print()

arr = arr.reshape(3,3) 

print(arr,arr.shape)

[[1 2 3 4 5 6 7 8 9]] (1, 9)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [15]:
#5]
arr1 = np.array([ [1,2,3] , [3,2,1] , [4,3,2] ])
arr2 = np.array([ [5,4,3] , [5,4,5] , [5,6,7] ])

print(np.vstack((arr1,arr2))) # Stack the arrays in a row-wise sequence
print() 
print(np.hstack((arr1,arr2))) # Stack the arrays in a column-wise sequence

[[1 2 3]
 [3 2 1]
 [4 3 2]
 [5 4 3]
 [5 4 5]
 [5 6 7]]

[[1 2 3 5 4 3]
 [3 2 1 5 4 5]
 [4 3 2 5 6 7]]


In [20]:
#6]
arr = np.array([ [1,2,2] , [3,4,4] , [5,6,6] ])
arr2=np.unique(arr)
print(arr2)
print(arr2.size)


[1 2 3 4 5 6]
6
